### ISSUE TITLE
Mention `set (scalaJSStage in Test) := FastOptStage`

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js-website#110]
`set scalaJSStage := FastOptStage` only works for `run` and not `test`, and that's not obvious. I'd guess more people use `test` from the command line than use `run`* . Took me a few minutes to figure it out, and I probably know this stuff better than anyone*

*Citation Needed

**Comment by ochrons** [comment]
This seems to be fixed in docs.

**Comment by sjrd** [comment]
Yes, this is fixed.
