### ISSUE TITLE
`String.substring(start, end)` behaves different on scala and scalajs

### ISSUE THREAD

**Issue by freewind** [scala-js/scala-js-website#130]
For the code:

```scala
"abcdefg".substring(3, 1)
```
It will throw exception when running with normal Scala:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1937)
```

But will get a substring without any exception with scala.js:

```
bc
```

Shall we make them consistent?

**Comment by sjrd** [comment]
This is not the right issue tracker. Head to the [scala-js](https://github.com/scala-js/scala-js/issues) repo.

That said, no, we won't make consistent, because `StringIndexOutOfBounds` is undefined behavior in Scala.js.
