### ISSUE TITLE
Mention source map support for Node.js in tutorial

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js-website#139]

**Comment by yawnt** [comment]
where does the npm package need to be installed ? in / ? in target/ ?
thanks!

**Comment by sjrd** [comment]
Globally on your system, either on a user basis or as root.

**Comment by gzm0** [comment]
You can also install it in the folder of your Scala.js project (which is `npm`'s default IIRC).

**Comment by yawnt** [comment]
@gzm0 I have `source-map-support` installed, the .map file is generated and the `//# sourceMap` added to the compiled .js, however I keep getting the compiled JS stacktraces.. what am I doing wrong? could it be because i'm using NVM and not vanilla node?
thanks!

**Comment by gzm0** [comment]
What happens if you launch `node` (in a console) and type:

```javascript
require('source-map-support').install();
```

If this fails, it is a problem with your setup.

If you could also try to see if chrome gives you source maps. If not, its a problem with the linking.

If both of these work as expected, all I can recommend you is to try and load your code manually in a node shell and see if that works. But at that point I guess I'd need to copy your setup to fiddle around...

**Comment by yawnt** [comment]
the require works.. i will try chrome tomorrow because I don't have the code here atm... 
the only peculiarity about my setup is that i am using iojs with NVM (and not a standard nodejs install from the distro package manager), but I can't see how that could cause the issue

OS is ArchLinux x86_64 btw
thanks!

**Comment by yawnt** [comment]
ok, I did find the code after all, source maps work in Chrome!

**Comment by gzm0** [comment]
Hmmm... That's the worst case... In this case the source map support does not work properly in your setup (or just "differently"...)

Could you get any source map to work so far in your setup?

**Comment by yawnt** [comment]
yes, if I use typescript (as described in the demo section of source-map-support's README) it works flawlessly

here's my code

```scala
package hai
import scala.scalajs.js.JSApp

object SimpleRouterSetup extends JSApp {
  def main(): Unit = {
    throw new Error("asd")
  }
}
```

here is the result of the repl
```
┌[yawnt@xantico] [/dev/pts/4]
└[~/Code/actor-test/target/scala-2.11]> node
> require('source-map-support').install()
undefined
> var a = require('./actor-test-fastopt.js')
> a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main()
java.lang.Error: asd
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log('error') }
error
undefined
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(e.stack) }
undefined
undefined
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(e instanceof Error) }
false
```
unless I'm reading this wrong, it looks like it's throwing something which is not an error?

my setup is iojs 2.3.1 installed using https://github.com/creationix/nvm on ArchLinux (kernel 4.0.7-2)

**Comment by sjrd** [comment]
Ah! I think I understand what's going on here. Source maps likely work fine. You should try to `printStackTrace()` the exception that is thrown by Scala.js.

As you now discovered, indeed, Scala.js exceptions are not subclasses of JavaScript `Error`s. They are subclasses of `java.lang.Throwable`, which inherits from `java.lang.Object`, and can therefore not inherit from `Error` as the same time. This means that JS VMs do not store a stack trace in our exceptions automatically. Instead, we have to throw an `Error` internally and catch its stack trace, which we then decode to be put in `Throwable.getStackTrace()` and is used by `Throwable.printStackTrace()`. But as far as the VM knows, it's still not an `Error` ...

**Comment by yawnt** [comment]
mmm 

```
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(e.printStackTrace()) }
TypeError: e.printStackTrace is not a function
    at repl:1:31
    at REPLServer.defaultEval (repl.js:154:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:308:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:209:10)
    at REPLServer.Interface._line (readline.js:548:8)
    at REPLServer.Interface._ttyWrite (readline.js:825:14)
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(Object.keys(e)) }
[ 's$1', 'e$1', 'stackTrace$1', 'stackdata' ]
undefined
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(e['stackTrace$1']) }
null
undefined
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(e['stackdata']) }
[TypeError: this.undef is not a function]
undefined
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(e['s$1']) }
asd
undefined
> try { a.__ScalaJSExportsNamespace.hai.SimpleRouterSetup().main() } catch(e) { console.log(e['e$1']) }
null
```

**Comment by sjrd** [comment]
Yes `printStackStrace()` is not `@JSExport`ed, so it's not visible to JS. You need to call that from Scala.js code.

**Comment by yawnt** [comment]
mmm no, nothing changes :/ .. but at any rate I have no idea where the code from Akka.js crashes, so I need to see the whole stacktrace (which happens in Chrome), I can't call printStackTrace explicitly

**Comment by gzm0** [comment]
Do you have something we can play around with?

**Comment by yawnt** [comment]
well, the snippet above that I pasted doesn't correctly work from node.js, so you can try that and tell me if it works in your install :)

**Comment by pauldraper** [comment]
So is there an example of stack traces working?

The tutorial just says "install this thing"; it's not clear at all what is supposed to happen.

**Comment by sjrd** [comment]
You can expect `run` and `test` to automatically show you stack traces in scala files.
