### ISSUE TITLE
Misleading remark about JVM options, in particular about PermGen

### ISSUE THREAD

**Issue by SeriousSoftware** [scala-js/scala-js-website#173]
The remark:
"Troubleshooting: Should you experience errors with the PermGen size of the JVM at this point, you can increase it. Refer, for example, to [this StackOverflow question](http://stackoverflow.com/questions/8331135/how-to-prevent-java-lang-outofmemoryerror-permgen-space-at-scala-compilation)."

should be reviewed. Since Java 8 the PermGen is removed.
1. The JVM options are difficult especially the memory control options.
2. The link to StackOverflow addresses old sbt versions.
3. The possibilities to set them in sbt are hidden and not so well documented. Hidden in a shell script I found [this](https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt#L94-L99) where IMHO `/etc/sbt/sbtopts` should be read as `${sbt_home}/conf/sbtconfig.txt`.

On my Windows machine I am using the Xmx JVM option, contents of `${sbt_home}/conf/sbtconfig.txt` is:

`````` shell
# Set the java args to high

-Xmx896M

-XX:ReservedCodeCacheSize=128m

# Set the extra SBT options

-Dsbt.log.format=true```

(With no PermGen options the the annoying "VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0" message will disappear.)
``````

**Comment by sjrd** [comment]
`git grep PermGen` says that we don't have this anymore.
