### ISSUE TITLE
Document scalajs-stubs

### ISSUE THREAD

**Issue by ozeebee** [scala-js/scala-js-website#178]
Some text could be added (in the "Cross-Building" page?) to describe how (and why) to export shared classes for JS usage.
I've spent some time searching for a solution before realizing it was already available in the form of the stubs library.
It could be a time saver for many people, IMHO.

**Comment by ochrons** [comment]
Could you do a PR for this? Since you have experience from the first-time-user perspective, it would be really valuable!

**Comment by ozeebee** [comment]
Created pull request https://github.com/scala-js/scala-js-website/pull/212.
