### ISSUE TITLE
Easier access to libraries (top level menu item)?

### ISSUE THREAD

**Issue by mkotsbak** [scala-js/scala-js-website#185]
From Gitter:

But where is the list of SJS wrappers in the new website?
That was one of the most useful parts in the last one

sjrd 12:17:
http://www.scala-js.org/community/libraries/
How did you search for it? Where were you expecting to see links to it that you did not find?

mkotsbak 12:18
A bit hidden. I looked at "community", but did not notice the menu on the right
What about a "LIBRARIES" top level menu?

sjrd 12:27
We could do that, yes.

ochrons 12:33
yea, the Community is a bit abstract, so Libraries top item would be good
although that then leaves the community part quite bare 

mkotsbak 12:33
No, I don't think so. It contains what you expect to find there
libs was 0 clicks in old webiste, so it should not be more than 1 click in the new
Actually it is two as there are sections
Sections could be dropdown menu or filters

**Comment by japgolly** [comment]
Oh good! I was going to submit an issue for exactly this :+1:

**Comment by ochrons** [comment]
Working on this now.
