### ISSUE TITLE
Documentation shows package object extending js.GlobalScope without @js.native

### ISSUE THREAD

**Issue by mseddon** [scala-js/scala-js-website#203]
Found by @bblfish here:

https://github.com/scala-js/scala-js-dom/pull/177#issuecomment-159743398

On this page:

http://www.scala-js.org/doc/interoperability/facade-types.html

There is a snippet of the documentation which shows a package object extending js.GlobalScope, but these will not compile because it lacks @js.native annotations.

**Comment by bblfish** [comment]
It will compile actually if the ` -Xfatal-warnings` is not set. But in any case it seems to be deprecated, so that the example in the documenation should remove the package object example, and explain instead the preferred  method explained by sjrd in issue 177
