### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js-website#206]
Use a client-side search library like lunr.js to provide basic search functionality.

**Comment by japgolly** [comment]
:100:

**Comment by japgolly** [comment]
React are adding search to their gh-pages in this PR:
https://github.com/facebook/react/pull/6202/files

Looks pretty easy to copy for our purposes.
Basically create a free account with https://community.algolia.com/docsearch/, then add a few lines to site.

**Comment by sjrd** [comment]
This was done in #209, actually.
