### ISSUE TITLE
Clipboard is not defined

### ISSUE THREAD

**Issue by cranst0n** [scala-js/scala-js-website#218]
On the __Testing__ page, the copy to clipboard functionality for the test frameworks doesn't work.

Chrome `(Version 47.0.2526.106 (64-bit)-Linux)` console complains:
`testing.html:176 Uncaught ReferenceError: Clipboard is not defined`.

**Comment by ochrons** [comment]
This is now fixed as the Clipboard is initialized at a correct stage.

**Comment by sjrd** [comment]
Close?

**Comment by ochrons** [comment]
Yes, can be closed. The error is not there anymore and clipboard works ok.
