### ISSUE TITLE
Anchors hide the top of the section below the floating header

### ISSUE THREAD

**Issue by dwijnand** [scala-js/scala-js-website#241]
For example if you click https://www.scala-js.org/community/#open-source-scalajs-projects the "Open Source Scala.js projects" title won't be visible.

I'm opening this ticket because we also had this issue in sbt's website: https://github.com/sbt/website/issues/117 which was fixed (albeit, a tad bit crudely..).

**Comment by sjrd** [comment]
@ochrons Hadn't we fixed that already, at some point? Did it come back, then?

**Comment by ochrons** [comment]
Yes, this was fixed at some point. Gotta check why it's back :)
