### ISSUE TITLE
recent versions are missing from version history page

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js-website#270]
http://www.scala-js.org/doc/internals/history.html stops at 0.6.5

**Comment by sjrd** [comment]
Woops, indeed. I usually look at https://www.scala-js.org/news/ for the history, so I forgot that page. Thanks for the report.

**Comment by SethTisue** [comment]
this hasn't shown up at http://www.scala-js.org/doc/internals/history.html ?

**Comment by sjrd** [comment]
No :-( See #274
