### ISSUE TITLE
Facade writing - best practices

### ISSUE THREAD

**Issue by lastsys** [scala-js/scala-js-website#292]
I intend to write a page about best practices when writing facades. IMHO writing facades has been the most difficult part of learning ScalaJS and I believe many beginners would benefit from such a page.

I also expect the contents of such a page to be up for a lot of debate.

Please add any opinions on the subject in this issue and I will collect them.

Items to cover (list WIP):
- Alternatives to handle enumerations of various kinds. List how different JS-libs create enumerations and how to approach those in a facade. Good and bad.
- Alternatives to handle different combinations of arguments to a single JS-function. Good and bad.
- Alternatives to handle many different return types from a single JS-function. Good and bad.
- Alternatives to handle pure JS-objects. Many topics here, JS-objects as arguments, as return types. Good and bad.
- Using native JS-objects and handling `null`, `undefined`, `empty objects` vs. parsing to `case class`. Mutability vs. immutability. Good and bad.
- Class constructors for JS. Multiple constructor alternatives.
- Level of facade, PIMPL, wrappers or direct mapping.
- `js.Any` and `String`, `Int` and such in pattern matching.
- Cases when libs relies on dynamic loading of many smaller js-files vs. ScalaJS having a single js-file. (like OpenUI5 views with dynamic loading of XML and js-files).

**Comment by jducoeur** [comment]
My thoughts on the subject can be found in [this article in Querki](https://www.querki.net/u/jducoeur/scala-notes/#!Creating-a-Scalajs-Facade-for-a-jQuery-Widget).  That's a bit more "how to do it" than best practices per se, but probably useful food for thought...

**Comment by lastsys** [comment]
Thanks. Covers a lot of ground but not everything I have been thinking about.

**Comment by lastsys** [comment]
I have not been able to work with Scala for a long time so I am closing this issue.
