### ISSUE TITLE
typo in annotation name

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js-website#354]
https://github.com/scala-js/scala-js-website/blob/master/_posts/news/2017-03-21-announcing-scalajs-0.6.15.md

```@scala.scalajs.reflect.annotation.EnableReflectiveInstantion```
should be
```@scala.scalajs.reflect.annotation.EnableReflectiveInstantiation```

**Comment by sjrd** [comment]
Duh ... Thanks for the report.

**Comment by gzm0** [comment]
Whoa... you scared me... For a second I thought the typo is in the actual annotation :P

**Comment by andreaTP** [comment]
It take me more time to fix all copy pasted errors made at first then to have new Reflect working in Akka.Js
Great work guys thanks!

**Comment by gzm0** [comment]
Fixed in 6768fc8b9f05ce4c19f1e50c7bd8bcad1fd8eefc.
