### ISSUE TITLE
Mention DefinitelyScala in page http://www.scala-js.org/libraries/facades.html

### ISSUE THREAD

**Issue by zoosky** [scala-js/scala-js-website#363]
Open source Scala.js facades for some of your favorite JavaScript libraries, derived from DefinitelyTyped's TypeScript definitions.

See https://definitelyscala.com/

**Comment by sjrd** [comment]
PR welcome.

**Comment by zoosky** [comment]
So this seems to be outdated? 

"Additions and corrections to this section may be reported through GitHub issues. Please include Name, Url, Description and Dependency" in https://github.com/scala-js/scala-js-website/blob/master/libraries/libs.md

**Comment by sjrd** [comment]
It's not outdated. An issue will eventually get fixed, the next time I batch-process those additions. A PR typically gets in more quickly.
