### ISSUE TITLE
Crossbuilding SBT example is misleading

### ISSUE THREAD

**Issue by baank** [scala-js/scala-js-website#393]
On this page: https://www.scala-js.org/doc/project/cross-build.html

Below this line: "This is an example how your build.sbt could look like:"

Is an SBT example that would never actually work since it is missing the enablePlugins(ScalaJSPlugin) line. It would be good to add it in.

**Comment by sjrd** [comment]
The example is correct. In a `crossProject`, you must not use `enablePlugins(ScalaJSPlugin)`, as it would then also apply on the JVM project. `crossProject` enables the plugin automatically, and only on the JS part.

**Comment by baank** [comment]
Can we reopen this and add to that page that you should not use enablePlugins for crossProjects.

**Comment by sjrd** [comment]
#394
