### ISSUE TITLE
document how interop works with exceptions

### ISSUE THREAD

**Issue by aappddeevv** [scala-js/scala-js-website#406]
i.e. throwing an exception in scala, what can js catch? and vice versa.

I did not see this in the docs.

**Comment by sjrd** [comment]
The gist is:

* Scala.js throws an instance of `js.JavaScriptException` -> JS catches the wrapped value
* Scala.js throws something else (necessarily a `Throwable`) -> JS catches it as is
* JS throws an instance of Scala.js' `Throwable` -> Scala.js catches it as is
* JS throws something else -> Scala.js catches it as wrapped in a `js.JavaScriptException`

**Comment by aappddeevv** [comment]
What if you need to throw a Promise? i.e. something that is a not a Throwable and have JS catch it?

I cast a Promise to a Throwable to make scala.js throw and I'm almost to the point where I can test to see if js is catching it. Will that work?

**Comment by sjrd** [comment]
First bullet above -> `throw js.JavaScriptException(thePromise)` means that JS will catch `thePromise`.

You cannot cast `thePromise` to `Throwable` because it's not a `Throwable`.

**Comment by aappddeevv** [comment]
I think that covers the interop cases. Thanks.

**Comment by aappddeevv** [comment]
I'll put a PR together for this content in the docs.
