### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by juancarlosfarah** [scala-js/scala-js-website#455]
I've been trying to reach your website, but it looks like it's down? I get the following message from Cloudflare:

![image](https://user-images.githubusercontent.com/1707188/62731465-84223700-ba22-11e9-8bde-1352447a51c5.png)

**Comment by sjrd** [comment]
Yes, it's on the service provider of the server. They're on it, but I don't know much else for know.

**Comment by juancarlosfarah** [comment]
Thanks for your reply! Website is still down, but I have managed to run a copy locally, so I can read the docs.

**Comment by sjrd** [comment]
It's back online.
