### ISSUE TITLE
Scaladocs are published in legacy look and feel 

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js-website#467]
Scaladocs listed in https://www.scala-js.org/doc/api.html stil uses legacy look and feel, which are used in Scala 2.11 and prior.

I think the new look and feel, landed in Scala 2.12, has some advantanges.
E.g. single powerful search bar (can also search members), bigger fonts, eye-friendly background color, and so on.

It would be good if Scaladocs are re-published in latest Scala (2.13 as of today)'s styling.

**Comment by sjrd** [comment]
Because of https://github.com/scala/bug/issues/10029, upgrading the look and feel would break existing links, so I decided not to do that. The Scaladoc for 1.x are built with the new style.
