### ISSUE TITLE
Latest and 1.0.1 Scaladocs are broken

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js-website#488]
The links from here:
https://www.scala-js.org/doc/api.html

Are broken, both:
https://www.scala-js.org/api/scalajs-library/latest/scala/scalajs/js/index.html
https://www.scala-js.org/api/scalajs-library/1.0.1/scala/scalajs/js/index.html

results in `Not Found`

**Comment by sjrd** [comment]
Thanks for the report. Everything should be fixed now.

**Comment by andreaTP** [comment]
it is indeed, thanks for the quick fix!
