### ISSUE TITLE
Make documentation for Scala 3

### ISSUE THREAD

**Issue by FabioPinheiro** [scala-js/scala-js-website#547]
The documentation and tutorials needs to be reviewed to account for the new Scala 3 version.

**Comment by sjrd** [comment]
To anyone coming here before we adapt anything, please note that:

* Take any Scala.js documentation, and set `scalaVersion := "3.0.0"`
* You may have to adapt `libraryDependencies`, just like in any Scala project.
* That's it.

There is no difference in how one uses Scala.js in Scala 3 compared to Scala 2.

**Comment by sjrd** [comment]
The main tutorial has been using Scala 3 for a while now.
