### ISSUE TITLE
Link to Scaladoc is broken

### ISSUE THREAD

**Issue by vincenzobaz** [scala-js/scala-js-website#550]
the link to scaladoc in https://www.scala-js.org/doc/interoperability/types.html is broken
![image](https://user-images.githubusercontent.com/6325220/122532409-c2c2a880-d020-11eb-806d-2d58ad5272b6.png)

**Comment by gzm0** [comment]
Fixed in 6a6ac80da07140668ef8cf69c53b710530a55168
