### ISSUE TITLE
mUnit should be listed at the testing framworks page

### ISSUE THREAD

**Issue by frankbe** [scala-js/scala-js-website#638]
mUnit is the testing library of scala toolkit and it does support scala.js.
IMO it's supposed to be listed at the testing framework page, so.
Maybe even in the first place since the toolkit tools somehow can be considered as default solutions.

**Comment by sjrd** [comment]
PR welcome. ;)

**Comment by frankbe** [comment]
PR created. Against my advice, I put it second on the list as JUnit with its own plugin (ScalaJSJUnitPlugin) seems to play a special role. Feel free to change the order as needed.
